### ISSUE TITLE
Add a way to silence all warnings

### ISSUE THREAD

**Issue by LukaHorvat** [DanielSchuessler/th-expand-syns#8]
Currently I'm getting a lot of these with my code

     th-expand-syns: WARNING: Don't know how to interpret the result of reify GHC.TypeLits.Text

and similar. I'm assuming the library is having issues with promoted data constructors. I'm fine with assuming they're not type synonyms but I'd like a way to suppress the warnings.

**Comment by DanielSchuessler** [comment]
I just uploaded a version which eliminates these warnings (commit 4979213b851a30464f00c6afa1adeae867833128).

That leaves the warning about type families (which can already be disabled) as the only remaining warning at the moment. I agree that each kind of warning should have a flag to suppress it, but I'm hesitant to add a flag to suppress *all* warnings, because critical warnings may be added in the future.
